/*
 *  File: keys.h
 *  Last Updated: 18/08/2012
 *  Coded By: Erick Luis Moraes de Sousa
 *  Contact: elms1990 (at) gmail.com
 */

#ifndef __KEYS_H__
#define __KEYS_H__

#include <SDL2/SDL.h>
namespace Polymorphic {

    typedef enum {
        //ascii mapped keys
        KEY_BACKSPACE = SDL_SCANCODE_BACKSPACE, 
        KEY_TAB = SDL_SCANCODE_TAB, 
        KEY_CLEAR = SDL_SCANCODE_CLEAR, 
        KEY_RETURN = SDL_SCANCODE_RETURN, 
        KEY_PAUSE = SDL_SCANCODE_PAUSE,  
        KEY_ESCAPE = SDL_SCANCODE_ESCAPE,
        KEY_SPACE = SDL_SCANCODE_SPACE,
        KEY_EXCLAMATION = SDL_SCANCODE_KP_EXCLAM,
        KEY_HASH = SDL_SCANCODE_KP_HASH,
        KEY_AMPERSAND = SDL_SCANCODE_KP_AMPERSAND,
        KEY_LPARENT = SDL_SCANCODE_KP_LEFTPAREN,
        KEY_RPARENT = SDL_SCANCODE_KP_RIGHTPAREN,
        KEY_PLUS = SDL_SCANCODE_KP_PLUS,
        KEY_COMMA = SDL_SCANCODE_COMMA,
        KEY_PERIOD = SDL_SCANCODE_PERIOD,
        KEY_SLASH = SDL_SCANCODE_SLASH,
        KEY_0 = SDL_SCANCODE_0,
        KEY_1 = SDL_SCANCODE_1,
        KEY_2 = SDL_SCANCODE_2,
        KEY_3 = SDL_SCANCODE_3,
        KEY_4 = SDL_SCANCODE_4,
        KEY_5 = SDL_SCANCODE_5,
        KEY_6 = SDL_SCANCODE_6,
        KEY_7 = SDL_SCANCODE_7,
        KEY_8 = SDL_SCANCODE_8,
        KEY_9 = SDL_SCANCODE_9,
        KEY_COLON = SDL_SCANCODE_KP_COLON,
        KEY_SEMICOLON = SDL_SCANCODE_SEMICOLON,
        KEY_LESS = SDL_SCANCODE_KP_LESS,
        KEY_EQUAL = SDL_SCANCODE_EQUALS, 
        KEY_GREATER = SDL_SCANCODE_KP_GREATER,
        KEY_AT = SDL_SCANCODE_KP_AT,
        KEY_LBRACKET = SDL_SCANCODE_LEFTBRACKET,
        KEY_BACKSLASH = SDL_SCANCODE_BACKSLASH,
        KEY_RBRACK = SDL_SCANCODE_RIGHTBRACKET,
        KEY_A = SDL_SCANCODE_A,  //mapped as lower case ascii codes
        KEY_B = SDL_SCANCODE_B,
        KEY_C = SDL_SCANCODE_C,
        KEY_D = SDL_SCANCODE_D,
        KEY_E = SDL_SCANCODE_E,
        KEY_F = SDL_SCANCODE_F,
        KEY_G = SDL_SCANCODE_G,
        KEY_H = SDL_SCANCODE_H,
        KEY_I = SDL_SCANCODE_I,
        KEY_J = SDL_SCANCODE_J,
        KEY_K = SDL_SCANCODE_K,
        KEY_L = SDL_SCANCODE_L,
        KEY_M = SDL_SCANCODE_M,
        KEY_N = SDL_SCANCODE_N,
        KEY_O = SDL_SCANCODE_O,
        KEY_P = SDL_SCANCODE_P,
        KEY_Q = SDL_SCANCODE_Q,
        KEY_R = SDL_SCANCODE_R,
        KEY_S = SDL_SCANCODE_S,
        KEY_T = SDL_SCANCODE_T,
        KEY_U = SDL_SCANCODE_U,
        KEY_V = SDL_SCANCODE_V,
        KEY_W = SDL_SCANCODE_W,
        KEY_X = SDL_SCANCODE_X,
        KEY_Y = SDL_SCANCODE_Y,
        KEY_Z = SDL_SCANCODE_Z,
        KEY_DELETE = SDL_SCANCODE_DELETE,
        //end of ascii mapped keys

        //Num pad keys
        KEY_NUM0 = SDL_SCANCODE_KP_0,
        KEY_NUM1 = SDL_SCANCODE_KP_1,
        KEY_NUM2 = SDL_SCANCODE_KP_2,
        KEY_NUM3 = SDL_SCANCODE_KP_3,
        KEY_NUM4 = SDL_SCANCODE_KP_4,
        KEY_NUM5 = SDL_SCANCODE_KP_5,
        KEY_NUM6 = SDL_SCANCODE_KP_6,
        KEY_NUM7 = SDL_SCANCODE_KP_7,
        KEY_NUM8 = SDL_SCANCODE_KP_8,
        KEY_NUM9 = SDL_SCANCODE_KP_9,
        KEY_NUM_PERIOD = SDL_SCANCODE_PERIOD,
        KEY_NUM_DIVIDE = SDL_SCANCODE_KP_DIVIDE,
        KEY_NUM_MULTIPLY = SDL_SCANCODE_KP_MULTIPLY,
        KEY_NUM_MINUS = SDL_SCANCODE_KP_MINUS,
        KEY_NUM_PLUS = SDL_SCANCODE_KP_PLUS,
        KEY_NUM_ENTER = SDL_SCANCODE_KP_ENTER,
        KEY_NUM_EQUAL = SDL_SCANCODE_KP_EQUALS,

        //Arrows, Home pad and Function Keys
        KEY_UP = SDL_SCANCODE_UP,
        KEY_DOWN = SDL_SCANCODE_DOWN,
        KEY_RIGHT = SDL_SCANCODE_RIGHT,
        KEY_LEFT = SDL_SCANCODE_LEFT,
        KEY_INSERT = SDL_SCANCODE_INSERT,
        KEY_HOME = SDL_SCANCODE_HOME,
        KEY_END = SDL_SCANCODE_END,
        KEY_PAGEUP = SDL_SCANCODE_PAGEUP,
        KEY_PAGEDOWN = SDL_SCANCODE_PAGEDOWN,
        KEY_F1 = SDL_SCANCODE_F1,
        KEY_F2 = SDL_SCANCODE_F2,
        KEY_F3 = SDL_SCANCODE_F3,
        KEY_F4 = SDL_SCANCODE_F4,
        KEY_F5 = SDL_SCANCODE_F5,
        KEY_F6 = SDL_SCANCODE_F6,
        KEY_F7 = SDL_SCANCODE_F7,
        KEY_F8 = SDL_SCANCODE_F8,
        KEY_F9 = SDL_SCANCODE_F9,
        KEY_F10 = SDL_SCANCODE_F10,
        KEY_F11 = SDL_SCANCODE_F11,
        KEY_F12 = SDL_SCANCODE_F12,

        //Key state modifiers
        KEY_NUMLOCK = SDL_SCANCODE_NUMLOCKCLEAR,
        KEY_CAPSLOCK = SDL_SCANCODE_CAPSLOCK,
        KEY_SCROLL_LOCK = SDL_SCANCODE_SCROLLLOCK,
        KEY_RSHIFT = SDL_SCANCODE_RSHIFT,
        KEY_LSHIFT = SDL_SCANCODE_LSHIFT,
        KEY_RCTRL = SDL_SCANCODE_RCTRL,
        KEY_LCTRL = SDL_SCANCODE_LCTRL,
        KEY_RALT = SDL_SCANCODE_RALT,
        KEY_LALT = SDL_SCANCODE_LALT

    } Keys;

}
#endif /* __KEYS_H__ */
